# Autogenerated wrapper script for NRLMSIS_jll for x86_64-w64-mingw32-libgfortran3
export nrlmsis

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("NRLMSIS")
JLLWrappers.@declare_library_product(nrlmsis, "nrlmsis.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        nrlmsis,
        "bin\\nrlmsis.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
